apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: flask-app
        imagePullPolicy: Never
        env:
        - name: MYSQL_DATABASE_HOST
          value: "mysql-svc"
        - name: MYSQL_DATABASE_DB
          value: "syseng-devops-assignment"
        - name: "MYSQL_DATABASE_USER"
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mysql-database-user
        - name: MYSQL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mysql-database-password
        ports:
        - containerPort: 5001
