apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
data:
  default_auth: |
    [mysqld]
    default_authentication_plugin=mysql_native_password
    innodb_use_native_aio = 0
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
